# This `Makefile` is showing you some new stuff with `make`.
# First, we set `CFLAGS` in the file so we never have to set it
# again, as well as adding the `-g` flag to get debugging.
# Then, we have a section named `clean` that tells `make` how to
# clean up our little project.

CFLAGS=-Wall -g

# Extra Credit: build `ex3` with just the command `make`
all: ex3

clean:
		rm -f ex3
